version: "3.9"
services:
  codezingerbot:
    container_name: codezinger-scraper
    image: ghcr.io/roguedbear/codezinger-due-date-scraper:2.0.2
    build: .
    restart: unless-stopped
    environment:
      TZ: Asia/Calcutta
      AVATAR_URL: https://cdn.discordapp.com/attachments/794508344441700382/935525972722188329/when_python_loses_Custom.png
      WEBHOOK_USERNAME: dockerbone
      CODEZINGER_DASHBOARD: https://labs.codezinger.com/student/dashboard

    volumes:
      - ./crontab.txt:/etc/codezinger-bot.d/jobs
      - ${PWD}/db.db:/app/db/question_data.db # to make the db persistent
      - ./config.yml:/app/config.yml # if you dont have custom names, comment out this line
    secrets:
      - WEBHOOK_URL
      - EMAIL
      - PASSWORD

# Dont forget to do `chmod -R 400 secrets/` to make the files
# read only for your user
secrets:
  WEBHOOK_URL:
    file: ./secrets/webhook_url.txt
  EMAIL:
    file: ./secrets/email.txt
  PASSWORD:
    file: ./secrets/password.txt
