name: upload draft

on:
  release:
    types: [published, created]
  push:
    paths:
      - ".github/workflows/release.yml"

jobs:
  upload-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            config.yml.EXAMPLE
            crontab.txt.EXAMPLE
            docker-compose.yml
            docker-compose-multiple-accounts-example.yml
